### ISSUE TITLE
Intellij IDEA Ultimate 191 with Scala v2019.1.6 on Mac OS Exception

### ISSUE THREAD

**Issue by cassiuscai** [xylo/intellij-postfix-templates#107]
```java
com.intellij.diagnostic.PluginException: java.lang.reflect.InvocationTargetException [Plugin: de.endrullis.idea.postfixtemplates]
	at com.intellij.util.ExtensionInstantiator.instantiateWithPicoContainerOnlyIfNeeded(ExtensionInstantiator.java:58)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:21)
	at com.intellij.lang.LanguageExtensionPoint.lambda$new$0(LanguageExtensionPoint.java:22)
	at com.intellij.openapi.util.NotNullLazyValue$2.compute(NotNullLazyValue.java:68)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
	at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:27)
	at com.intellij.codeInsight.template.postfix.settings.PostfixTemplateStorage.<init>(PostfixTemplateStorage.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:92)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.createAndInitialize(ServiceManagerImpl.java:222)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.lambda$getComponentInstance$0(ServiceManagerImpl.java:209)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:192)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:211)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:52)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:26)
	at com.intellij.codeInsight.template.postfix.settings.PostfixTemplateStorage.getInstance(PostfixTemplateStorage.java:50)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplatesUtils.getAvailableTemplates(PostfixTemplatesUtils.java:45)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.getLookupElements(PostfixLiveTemplate.java:218)
	at com.intellij.codeInsight.template.CustomLiveTemplateBase.addCompletions(CustomLiveTemplateBase.java:53)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.showCustomLiveTemplates(LiveTemplateCompletionContributor.java:157)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.access$100(LiveTemplateCompletionContributor.java:38)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:85)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:161)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:90)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:120)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:60)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:828)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:813)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:280)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:277)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.intellij.util.ExceptionUtilRt.rethrow(ExceptionUtilRt.java:31)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:411)
	at com.intellij.util.ExtensionInstantiator.instantiateWithPicoContainerOnlyIfNeeded(ExtensionInstantiator.java:41)
	... 56 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:392)
	... 57 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class de.endrullis.idea.postfixtemplates.languages.scala.CustomScalaStringPostfixTemplate
	at de.endrullis.idea.postfixtemplates.languages.scala.ScalaStringPostfixTemplateCreator.createTemplate(ScalaStringPostfixTemplateCreator.java:14)
	at de.endrullis.idea.postfixtemplates.languages.scala.ScalaPostfixTemplateProvider.createTemplate(ScalaPostfixTemplateProvider.java:27)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.lambda$null$2(CustomPostfixTemplateProvider.java:175)
	at de.endrullis.idea.postfixtemplates.language.CptUtil.processTemplates(CptUtil.java:397)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.lambda$loadTemplatesFromVFiles$3(CustomPostfixTemplateProvider.java:166)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:940)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.loadTemplatesFromVFiles(CustomPostfixTemplateProvider.java:162)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.loadTemplatesFromFiles(CustomPostfixTemplateProvider.java:118)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.reloadTemplates(CustomPostfixTemplateProvider.java:101)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.reload(CustomPostfixTemplateProvider.java:93)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.<init>(CustomPostfixTemplateProvider.java:84)
	at de.endrullis.idea.postfixtemplates.languages.scala.ScalaPostfixTemplateProvider.<init>(ScalaPostfixTemplateProvider.java:11)
	... 62 more
```

**Comment by xylo** [comment]
The issue might be related to #110, since I cannot build the plugin for IDEA 2019.1.

**Comment by xylo** [comment]
I hope it is fixed in version 2.8.3.  Could you test it?

**Comment by cassiuscai** [comment]
![image](https://user-images.githubusercontent.com/2277724/55684852-a9267080-5982-11e9-9965-65d665bbd312.png)
In IDEA 2019.1, the plugin manager installed the plugin of the version <div style="color:red">**2.0.6**<div> by default

2.8.3 works for 2019.1

**Comment by xylo** [comment]
Oh, that's interesting.  Version 2.0.6 is really old.  :D

Good to here that 2.8.3 works. :)
