### ISSUE TITLE
Exception with Go templates

### ISSUE THREAD

**Issue by ORBAT** [xylo/intellij-postfix-templates#109]
Plugin version: 2.8.2.183

IDE:
GoLand 2019.1
Build #GO-191.6183.86, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2

Go templates in use: `pg.numbers`, `pg.collections` and `pg.misc`

Outcome: constant "IDE Fatal Error" events:

```
java.lang.NoSuchMethodError: com.goide.psi.impl.GoTypeUtil.isByteSlice(Lcom/goide/psi/GoType;)Z
	at de.endrullis.idea.postfixtemplates.languages.go.GoPostfixTemplatesUtils.lambda$static$7(GoPostfixTemplatesUtils.java:76)
	at de.endrullis.idea.postfixtemplates.languages.go.GoPostfixTemplatesUtils.lambda$goExp$13(GoPostfixTemplatesUtils.java:105)
	at com.intellij.openapi.util.Conditions$And.value(Conditions.java:179)
	at com.intellij.util.containers.ContainerUtil.findAll(ContainerUtil.java:1028)
	at com.intellij.util.containers.ContainerUtil.filter(ContainerUtil.java:1007)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateExpressionSelectorBase.getExpressions(PostfixTemplateExpressionSelectorBase.java:46)
	at de.endrullis.idea.postfixtemplates.templates.SimpleStringBasedPostfixTemplate$1.getExpressions(SimpleStringBasedPostfixTemplate.java:155)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateExpressionSelectorBase.hasExpression(PostfixTemplateExpressionSelectorBase.java:36)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateWithExpressionSelector.isApplicable(PostfixTemplateWithExpressionSelector.java:64)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.lambda$createIsApplicationTemplateFunction$4(PostfixLiveTemplate.java:300)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.getLookupElements(PostfixLiveTemplate.java:220)
	at com.intellij.codeInsight.template.CustomLiveTemplateBase.addCompletions(CustomLiveTemplateBase.java:53)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.showCustomLiveTemplates(LiveTemplateCompletionContributor.java:157)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.access$100(LiveTemplateCompletionContributor.java:38)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:85)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:161)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:90)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:120)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:60)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:828)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:813)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:280)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:277)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xylo** [comment]
I fixed this already in the code base.  But there is a problem with building the plugin at the moment.

**Comment by xylo** [comment]
Fixed in version 2.8.3.

**Comment by ORBAT** [comment]
Thanks! Also, thank you for the great plugin, it's more or less a must-have with Go which tends to be a bit boilerplate-heavy at times

**Comment by xylo** [comment]
Thanks. :)
