### ISSUE TITLE
Plugin is incompatible to IDEA 2019.2

### ISSUE THREAD

**Issue by VictorGranetski** [xylo/intellij-postfix-templates#122]
com.intellij.diagnostic.PluginException: java.lang.reflect.InvocationTargetException [Plugin: de.endrullis.idea.postfixtemplates]
	at com.intellij.util.ExtensionInstantiator.instantiateWithPicoContainerOnlyIfNeeded(ExtensionInstantiator.java:58)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:21)
	at com.intellij.lang.LanguageExtensionPoint.lambda$new$0(LanguageExtensionPoint.java:31)
	at com.intellij.openapi.util.NotNullLazyValue$2.compute(NotNullLazyValue.java:67)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:38)
	at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:36)
	at com.intellij.codeInsight.template.postfix.settings.PostfixTemplateStorage.<init>(PostfixTemplateStorage.java:39)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:88)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:66)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:48)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.createAndInitialize(ServiceManagerImpl.java:242)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.lambda$getComponentInstance$0(ServiceManagerImpl.java:227)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:192)
	at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:229)
	at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:246)
	at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:213)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:52)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:26)
	at com.intellij.codeInsight.template.postfix.settings.PostfixTemplateStorage.getInstance(PostfixTemplateStorage.java:48)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplatesUtils.getAvailableTemplates(PostfixTemplatesUtils.java:45)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.getLookupElements(PostfixLiveTemplate.java:218)
	at com.intellij.codeInsight.template.CustomLiveTemplateBase.addCompletions(CustomLiveTemplateBase.java:53)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.showCustomLiveTemplates(LiveTemplateCompletionContributor.java:157)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.access$100(LiveTemplateCompletionContributor.java:38)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:85)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:37)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:150)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:119)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:55)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:823)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:808)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:248)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1157)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:244)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:321)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:116)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:408)
	at com.intellij.util.ExtensionInstantiator.instantiateWithPicoContainerOnlyIfNeeded(ExtensionInstantiator.java:41)
	... 56 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:389)
	... 57 more
Caused by: java.lang.NoClassDefFoundError: org/jetbrains/plugins/scala/lang/completion/postfix/templates/selector/SelectorConditions
	at de.endrullis.idea.postfixtemplates.languages.scala.ScalaPostfixTemplatesUtils.isDescendant(ScalaPostfixTemplatesUtils.java:28)
	at de.endrullis.idea.postfixtemplates.languages.scala.ScalaPostfixTemplatesUtils.<clinit>(ScalaPostfixTemplatesUtils.java:14)
	at de.endrullis.idea.postfixtemplates.languages.scala.CustomScalaStringPostfixTemplate$1.<init>(CustomScalaStringPostfixTemplate.java:41)
	at de.endrullis.idea.postfixtemplates.languages.scala.CustomScalaStringPostfixTemplate.<clinit>(CustomScalaStringPostfixTemplate.java:39)
	at de.endrullis.idea.postfixtemplates.languages.scala.ScalaStringPostfixTemplateCreator.createTemplate(ScalaStringPostfixTemplateCreator.java:14)
	at de.endrullis.idea.postfixtemplates.languages.scala.ScalaPostfixTemplateProvider.createTemplate(ScalaPostfixTemplateProvider.java:27)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.lambda$null$2(CustomPostfixTemplateProvider.java:175)
	at de.endrullis.idea.postfixtemplates.language.CptUtil.processTemplates(CptUtil.java:397)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.lambda$loadTemplatesFromVFiles$3(CustomPostfixTemplateProvider.java:166)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:953)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.loadTemplatesFromVFiles(CustomPostfixTemplateProvider.java:162)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.loadTemplatesFromFiles(CustomPostfixTemplateProvider.java:118)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.reloadTemplates(CustomPostfixTemplateProvider.java:101)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.reload(CustomPostfixTemplateProvider.java:93)
	at de.endrullis.idea.postfixtemplates.templates.CustomPostfixTemplateProvider.<init>(CustomPostfixTemplateProvider.java:84)
	at de.endrullis.idea.postfixtemplates.languages.scala.ScalaPostfixTemplateProvider.<init>(ScalaPostfixTemplateProvider.java:11)
	... 62 more
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.scala.lang.completion.postfix.templates.selector.SelectorConditions PluginClassLoader[de.endrullis.idea.postfixtemplates, 2.0.6] com.intellij.ide.plugins.cl.PluginClassLoader@3f9bcd57
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:51)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 78 more

**Comment by xylo** [comment]
Exception occurs when completing a Java template, e.g. toDouble.

**Comment by xylo** [comment]
ATM there is no IDEA 2019.2 EAP release available for gradle.  So depending on that availability this issue might still take some time.  I created a forum post asking for the new release: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003985400-Cannot-find-IDEA-2019-2-EAP-release-that-can-be-downloaded-by-gradle
