### ISSUE TITLE
[Bug] Edit Variable Popup in "live template" settings does not open 

### ISSUE THREAD

**Issue by scdc** [xylo/intellij-postfix-templates#127]
In Webstorm Ide, the **Edit variables popup** in the **live templates** settings does not open due to custom postfix plugin

Plugin Name: Custom Postfix Template
Plugin Version: 2.10.1.191

WebStorm 2019.1.3
Build #WS-191.7479.14, built on May 27, 2019
JRE: 1.8.0_202-release-1483-b53 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

Error report:

java.lang.NoClassDefFoundError: com/intellij/codeInsight/template/JavaCodeContextType
	at de.endrullis.idea.postfixtemplates.templates.macro.SuggestShortVariableNameMacro.isAcceptableInContext(SuggestShortVariableNameMacro.java:110)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at

**Comment by xylo** [comment]
Oh. Thanks for the report.

**Comment by xylo** [comment]
Fixed in version 2.10.3.
