### ISSUE TITLE
java.lang.NoClassDefFoundError: com/intellij/lang/javascript/psi/JSExpression

### ISSUE THREAD

**Issue by AnielloFalcone** [xylo/intellij-postfix-templates#143]
Hi,

I am trying to use your plugin on WebStorm and create a Javascript template. 
Every time I try I get this:
```
java.lang.NoClassDefFoundError: com/intellij/lang/javascript/psi/JSExpression
	at de.endrullis.idea.postfixtemplates.languages.javascript.CustomJavaScriptStringPostfixTemplate.collectExpressions(CustomJavaScriptStringPostfixTemplate.java:94)
	at de.endrullis.idea.postfixtemplates.languages.javascript.CustomJavaScriptStringPostfixTemplate$2.getNonFilteredExpressions(CustomJavaScriptStringPostfixTemplate.java:144)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateExpressionSelectorBase.getExpressions(PostfixTemplateExpressionSelectorBase.java:46)
	at de.endrullis.idea.postfixtemplates.languages.javascript.CustomJavaScriptStringPostfixTemplate$2.getExpressions(CustomJavaScriptStringPostfixTemplate.java:153)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateExpressionSelectorBase.hasExpression(PostfixTemplateExpressionSelectorBase.java:36)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateWithExpressionSelector.isApplicable(PostfixTemplateWithExpressionSelector.java:64)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.lambda$createIsApplicationTemplateFunction$4(PostfixLiveTemplate.java:284)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.isApplicableTemplate(PostfixLiveTemplate.java:317)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.findApplicableTemplate(PostfixLiveTemplate.java:335)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.isApplicableTemplate(PostfixLiveTemplate.java:309)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.computeTemplateKey(PostfixLiveTemplate.java:86)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.prepareTemplate(TemplateManagerImpl.java:265)
	at com.intellij.codeInsight.template.impl.editorActions.ExpandLiveTemplateCustomAction$1.isEnabledForCaret(ExpandLiveTemplateCustomAction.java:52)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:102)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$isEnabled$1(EditorActionHandler.java:79)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$3(CaretModelImpl.java:354)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:453)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:346)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:336)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.isEnabled(EditorActionHandler.java:79)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.isEnabled(EditorActionHandler.java:141)
	at com.intellij.openapi.editor.actionSystem.EditorAction.update(EditorAction.java:120)
	at com.intellij.openapi.editor.actionSystem.EditorAction.updateForKeyboardAccess(EditorAction.java:124)
	at com.intellij.openapi.editor.actionSystem.EditorAction.update(EditorAction.java:157)
	at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:241)
	at com.intellij.openapi.editor.actionSystem.EditorAction.beforeActionPerformedUpdate(EditorAction.java:139)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:173)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:617)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:508)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:463)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:747)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

This is my template:

```
.log : console log
    ANY → console.log('$EXPR$ => ', $EXPR$);$END$
```

This is my Webstorm version:
```
WebStorm 2019.2.3
Build #WS-192.6817.13, built on September 24, 2019
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
```

I've trying using different setups for my template, ie. using `$expr$` instead of `$EXPR$` or other things, but always get that error.

Can you help me with this?

**Comment by xylo** [comment]
That's strange.  On my 64 bit Linux system it works with the same IDEA version:
```
WebStorm 2019.2.3
Build #WS-192.6817.13, built on September 24, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-29-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
```
Is your Custom Postfix Plugin up-to-date?
It should be version 2.10.7.192.

Moreover, you have to use $expr$ instead of $EXPR$.  But both versions should never throw an exception.

**Comment by remedialchaostheory** [comment]
Hi,

Same problem. Can't implement any custom JS template statements.
```
WebStorm 2019.2.3
Build #WS-192.6817.13, built on September 23, 2019
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
```

Custom template:
```
.ls : Console log with variable name
	ANY  →  console.log('$expr$', $expr$)
```

Thanks for the plugin btw. Very helpful in Pycharm (same computer, no issues).

**Comment by xylo** [comment]
Interesting. Today I could reproduce the bug on my system.
