### ISSUE TITLE
Updating templates fails due to PKI problem but reports "Success"

### ISSUE THREAD

**Issue by alshain** [xylo/intellij-postfix-templates#241]
![image](https://github.com/xylo/intellij-postfix-templates/assets/349397/8a462714-608c-457e-9082-de8994bd2ed4)

I'm behind a corporate proxy which I've configured in the IntelliJ settings.
The IntelliJ marketplace works, which is how I've installed your awesome plugin.

Any ideas what could be causing the below exception when trying to update the templates or what I could do to give you more debug information?

This exception occurs when I open the custom postfix settings dialog and when I hit on "update"

```
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1351)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1226)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1169)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:589)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
2024-05-07 10:23:23,865 [2682097]   INFO - STDERR - 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/java.net.URL.openStream(URL.java:1161)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at de.endrullis.idea.postfixtemplates.language.CptUtil.downloadWebTemplatesInfoFile(CptUtil.java:437)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at de.endrullis.idea.postfixtemplates.utils.CptUpdateUtils$1.run(CptUpdateUtils.java:98)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1335)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	... 43 more
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
2024-05-07 10:23:23,866 [2682098]   INFO - STDERR - 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
2024-05-07 10:23:23,867 [2682099]   INFO - STDERR - 	... 48 more
```

**Comment by xylo** [comment]
This is strange.  I'm also behind a corporate http proxy but for me it works.  Your exception shows that the download of the info file fails, which is [https://raw.githubusercontent.com/xylo/intellij-postfix-templates/master/templates/webTemplateFiles.yaml](https://raw.githubusercontent.com/xylo/intellij-postfix-templates/master/templates/webTemplateFiles.yaml)

Can you actually access the file via your web browser?

Maybe your proxy has some restrictions or maybe it tries to filter the https content by creating self-signed certificates.?
