### ISSUE TITLE
Conflicting template names

### ISSUE THREAD

**Issue by 1bytee** [xylo/intellij-postfix-templates#36]
Some template names are conflicting with inbuilt postfix templates (maybe since 2017.3 EAP). 

e.g. `.format`, `.stream`

Stacktrace:

```
Duplicated postfix completion key '.format' for language JAVA. Possible you need to disable one of the plugins: , de.endrullis.idea.postfixtemplates
java.lang.Throwable: Duplicated postfix completion key '.format' for language JAVA. Possible you need to disable one of the plugins: , de.endrullis.idea.postfixtemplates
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:136)
	at com.intellij.codeInsight.template.postfix.templates.LanguagePostfixTemplate.a(LanguagePostfixTemplate.java:55)
	at com.intellij.codeInsight.template.postfix.templates.LanguagePostfixTemplate.buildExtensions(LanguagePostfixTemplate.java:43)
	at com.intellij.codeInsight.template.postfix.templates.LanguagePostfixTemplate.buildExtensions(LanguagePostfixTemplate.java:28)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:116)
	at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:87)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.isApplicable(PostfixLiveTemplate.java:158)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.isApplicable(TemplateManagerImpl.java:305)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.listApplicableCustomTemplates(TemplateManagerImpl.java:568)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.a(LiveTemplateCompletionContributor.java:158)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.access$200(LiveTemplateCompletionContributor.java:49)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:98)
...
```

Shortened the stacktrace since only the error message is important

**Comment by xylo** [comment]
Thanks for the info.  I will look into this.  (Maybe it's possible to automatically deactivate the conflicting templates.)

**Comment by xylo** [comment]
Unfortunately, it's not possible to catch this exception somehow.  So I probably have to remove those postfix templates from the default ones although they don't really conflict with the IDEA ones regarding the matching type.  So another option would be to improve the handling of postfix templates in IDEA so that templates of the same name can have different origins.  Here is the feature request: https://youtrack.jetbrains.com/issue/IDEA-182045?query=postfix%20templates

**Comment by xylo** [comment]
Looks like JetBrains is not going to solve https://youtrack.jetbrains.com/issue/IDEA-182045.  So I deactivated the templates `.format` and `.stream` in the predefined templates.
However, if you have those templates already the plugin update will not change them automatically.  You either have to deactivate them manually or via the diff function.
