### ISSUE TITLE
AssertionError in scratches

### ISSUE THREAD

**Issue by yasuokav** [xylo/intellij-postfix-templates#65]
* Version: 1.8.5 (IDEA 2018.1.5)

It should be able to reproduce every time.

Details:
```
null
java.lang.AssertionError
	at de.endrullis.idea.postfixtemplates.languages.java.CustomJavaStringPostfixTemplate.lambda$withProjectClassCondition$2(CustomJavaStringPostfixTemplate.java:254)
	at com.intellij.openapi.util.Conditions$And.value(Conditions.java:179)
	at com.intellij.util.containers.ContainerUtil.findAll(ContainerUtil.java:1004)
	at com.intellij.util.containers.ContainerUtil.filter(ContainerUtil.java:983)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateExpressionSelectorBase.getExpressions(PostfixTemplateExpressionSelectorBase.java:60)
	at de.endrullis.idea.postfixtemplates.languages.java.CustomJavaStringPostfixTemplate$2.getExpressions(CustomJavaStringPostfixTemplate.java:166)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateExpressionSelectorBase.hasExpression(PostfixTemplateExpressionSelectorBase.java:50)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateWithExpressionSelector.isApplicable(PostfixTemplateWithExpressionSelector.java:62)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.lambda$createIsApplicationTemplateFunction$4(PostfixLiveTemplate.java:282)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.getLookupElements(PostfixLiveTemplate.java:214)
	at com.intellij.codeInsight.template.CustomLiveTemplateBase.addCompletions(CustomLiveTemplateBase.java:53)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.showCustomLiveTemplates(LiveTemplateCompletionContributor.java:161)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.access$200(LiveTemplateCompletionContributor.java:49)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:98)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:143)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:84)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:116)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:812)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:797)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:293)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:181)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:290)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by xylo** [comment]
Thanks for the bug report.  However, I don't know how to reproduce the bug.  I never discovered this behaviour.  Can you tell me more about the circumstances of this Exception?  

The exception tells me that the templates cannot be loaded because the file you are currently editing is not associated to any module of your project.  Can it be that the file you are editing is outside of your project root?  Or did you manage to create a project without any modules?  (I thought this is not possible)

**Comment by xylo** [comment]
OK, question solved.  Your file was most probably outside of your project root.  I just tested it and discovered the same issue.
