### ISSUE TITLE
Custom Postfix Templates sometimes throws an error in Goland

### ISSUE THREAD

**Issue by cedrickring** [xylo/intellij-postfix-templates#94]
I already tried out the new Go feature of this plugin but noticed that sometimes this error occurs:

```
java.lang.ClassCastException: com.goide.psi.impl.GoTypeReferenceExpressionImpl cannot be cast to com.goide.psi.GoExpression
	at de.endrullis.idea.postfixtemplates.languages.go.GoPostfixTemplatesUtils.lambda$static$1(GoPostfixTemplatesUtils.java:51)
	at com.intellij.openapi.util.Conditions$And.value(Conditions.java:179)
	at com.intellij.util.containers.ContainerUtil.findAll(ContainerUtil.java:1024)
	at com.intellij.util.containers.ContainerUtil.filter(ContainerUtil.java:1003)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateExpressionSelectorBase.getExpressions(PostfixTemplateExpressionSelectorBase.java:46)
	at de.endrullis.idea.postfixtemplates.templates.SimpleStringBasedPostfixTemplate$1.getExpressions(SimpleStringBasedPostfixTemplate.java:155)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateExpressionSelectorBase.hasExpression(PostfixTemplateExpressionSelectorBase.java:36)
	at com.intellij.codeInsight.template.postfix.templates.PostfixTemplateWithExpressionSelector.isApplicable(PostfixTemplateWithExpressionSelector.java:64)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.lambda$createIsApplicationTemplateFunction$4(PostfixLiveTemplate.java:283)
	at com.intellij.codeInsight.template.postfix.templates.PostfixLiveTemplate.getLookupElements(PostfixLiveTemplate.java:215)
	at com.intellij.codeInsight.template.CustomLiveTemplateBase.addCompletions(CustomLiveTemplateBase.java:53)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.showCustomLiveTemplates(LiveTemplateCompletionContributor.java:172)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor.access$200(LiveTemplateCompletionContributor.java:51)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:104)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:141)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:87)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:63)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:827)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:812)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$2(CodeCompletionHandlerBase.java:272)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:169)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$doComplete$3(CodeCompletionHandlerBase.java:269)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cedrickring** [comment]
@philipgriggs

**Comment by philipgriggs** [comment]
Hi Cedric. Thanks for the feedback. Can you give some more info about when this error occurs? Eg what is the expression you type in GoLand where it crashes? Thanks, Philip
